; ============================================================================
; Waffle PHP Profile: DEBUG (🐛)
; ============================================================================
; This profile activates Xdebug for detailed step-debugging and coverage,
; and disables the PHP JIT compiler for compatibility.
; ============================================================================

; Load Xdebug extension dynamically
zend_extension=xdebug.so

[xdebug]
; Enable debugging, development assistance, and code coverage
xdebug.mode=debug,develop,coverage
xdebug.start_with_request=yes
xdebug.discover_client_host=1
xdebug.client_port=9003
xdebug.log=/tmp/xdebug.log

[opcache]
; Disable JIT compiler as it is incompatible with Xdebug
opcache.jit=0
opcache.jit_buffer_size=0
